<a href="https://colab.research.google.com/github/Devil-92/Categorical_Feature_Encoding_Challenge_II/blob/main/notebooks/ApproachingCategoricalValues.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import os
base = '/content/drive/MyDrive/Projects/Projects'
for folder in ['input', 'src', 'models', 'notebooks']:
    os.makedirs(f'{base}/{folder}', exist_ok=True)

Categorial Variables can be classified into two major types :
- Nominal
- Ordinal

Nominal Values has no order associated with them whereas Ordinal Values has a order or ranking

Categorical Values are also classified as :
- Binary ( Male Female )
- Cyclic ( Days Of a week )

In [3]:
print('In this notebook we will use cat-in-the-dat datasets from Kaggle Categorical Features Encoding Challenge')

In this notebook we will use cat-in-the-dat datasets from Kaggle Categorical Features Encoding Challenge

In [4]:
from google.colab import userdata
os.environ['KAGGLE_API_TOKEN'] = userdata.get('Token')

In [5]:
import pandas as pd
import numpy as np

In [6]:
import kagglehub
import shutil

path = kagglehub.competition_download('cat-in-the-dat-ii')

input_folder = '/content/drive/MyDrive/Projects/Projects/input'

os.makedirs(input_folder, exist_ok=True)

for file_name in os.listdir(path):
    shutil.move(os.path.join(path, file_name), os.path.join(input_folder, file_name))

print("Files in input folder:", os.listdir(input_folder))

Files in input folder: ['test.csv', 'train.csv', 'sample_submission.csv', '.ipynb_checkpoints', 'cat_train_folds.csv']

In [7]:
df = pd.read_csv("/content/drive/MyDrive/Projects/Projects/input/train.csv")

In [8]:
df.head()

,id,bin_0,bin_1,bin_2,bin_3,bin_4,nom_0,nom_1,nom_2,nom_3,...,nom_9,ord_0,ord_1,ord_2,ord_3,ord_4,ord_5,day,month,target
0,0,0.0,0.0,0.0,F,N,Red,Trapezoid,Hamster,Russia,...,02e7c8990,3.0,Contributor,Hot,c,U,Pw,6.0,3.0,0
1,1,1.0,1.0,0.0,F,Y,Red,Star,Axolotl,NaN,...,f37df64af,3.0,Grandmaster,Warm,e,X,pE,7.0,7.0,0
2,2,0.0,1.0,0.0,F,N,Red,NaN,Hamster,Canada,...,NaN,3.0,NaN,Freezing,n,P,eN,5.0,9.0,0
3,3,NaN,0.0,0.0,F,N,Red,Circle,Hamster,Finland,...,f9d456e57,1.0,Novice,Lava Hot,a,C,NaN,3.0,3.0,0
4,4,0.0,NaN,0.0,T,N,Red,Triangle,Hamster,Costa Rica,...,c5361037c,3.0,Grandmaster,Cold,h,C,OZ,5.0,12.0,0

In [9]:
df.columns

Index(['id', 'bin_0', 'bin_1', 'bin_2', 'bin_3', 'bin_4', 'nom_0', 'nom_1',
       'nom_2', 'nom_3', 'nom_4', 'nom_5', 'nom_6', 'nom_7', 'nom_8', 'nom_9',
       'ord_0', 'ord_1', 'ord_2', 'ord_3', 'ord_4', 'ord_5', 'day', 'month',
       'target'],
      dtype='object')

In [10]:
df.ord_2.value_counts()

ord_2
Freezing       142726
Warm           124239
Cold            97822
Boiling Hot     84790
Hot             67508
Lava Hot        64840
Name: count, dtype: int64

In [11]:
print('This type of encoding is called Label Encoding')

This type of encoding is called Label Encoding

In [12]:
mapping = {
    'Freezing' : 0 ,
    'Warm' : 1 ,
    'Cold' : 2 ,
    'Boiling Hot' : 3 ,
    'Hot' : 4 ,
    'Lava Hot' : 5
}

In [13]:
df.loc[ : , 'ord_2'] = df.ord_2.map(mapping)

In [14]:
df.ord_2.value_counts()

ord_2
0.0    142726
1.0    124239
2.0     97822
3.0     84790
4.0     67508
5.0     64840
Name: count, dtype: int64

In [15]:
from sklearn import preprocessing

df = pd.read_csv("/content/drive/MyDrive/Projects/Projects/input/train.csv")

df.loc[ : , 'ord_2'] = df.ord_2.fillna('NONE')

lbl_enc = preprocessing.LabelEncoder()

df.loc[ : , 'ord_2'] = lbl_enc.fit_transform(df.ord_2.values)

We can use this directly in many tree-based models:
- Decision trees
- Random forest
- Extra Trees
- Or any kind of boosted trees model
- - XGBoost
- - GBM
- - LightGBM<br>

This type of encoding cannot be used in linear models, support vector machines or
neural networks as they expect data to be normalized (or standardized).

In [16]:
print('Binarizing data or say One hot enconding provides sparse data')

Binarizing data or say One hot enconding provides sparse data

In [17]:
example = np.random.randint(1000 , size = 1000000)

ohe = preprocessing.OneHotEncoder(sparse_output = False)

ohe_example = ohe.fit_transform(example.reshape(-1 , 1))

print(f"Size of dense matrix : {ohe_example.nbytes}")

ohe_sparse = preprocessing.OneHotEncoder(sparse_output = True)

ohe_example_sparse = ohe_sparse.fit_transform(example.reshape(-1 , 1))

print(f"Size of sparse matrix : {ohe_example_sparse.data.nbytes}")

full_size = (ohe_example_sparse.data.nbytes + ohe_example_sparse.indices.data.nbytes + ohe_example_sparse.indptr.nbytes)

print(f"Size of full sparse matix : {full_size}")

Size of dense matrix : 8000000000
Size of sparse matrix : 8000000
Size of full sparse matix : 16000004

In [18]:
print('The comparison is between 8 GB and 8 MB and hence sparse matrix are more easy to process')

The comparison is between 8 GB and 8 MB and hence sparse matrix are more easy to process

A matrix composed of many zeros is known as a sparse matrix. Sparse matrices have nice properties. How do you know if you have a sparse matrix? Use Matplotlib’s spy() method. Once you know your matrix is sparse, use Scipy’s CSR to convert its type from dense to sparse

In [19]:
print('We can also convert categorical variables to numerical variables')

We can also convert categorical variables to numerical variables

In [20]:
df.groupby(['ord_2'])['id'].count()

ord_2
0     84790
1     97822
2    142726
3     67508
4     64840
5     18075
6    124239
Name: id, dtype: int64

In [21]:
print('We can create a new column or replace this column by using the transform function of pandas along with groupby')

We can create a new column or replace this column by using the transform function of pandas along with groupby

In [22]:
df.groupby(['ord_2'])['id'].transform('count')

0          67508
1         124239
2         142726
3          64840
4          97822
           ...
599995    142726
599996     84790
599997    142726
599998    124239
599999     84790
Name: id, Length: 600000, dtype: int64

In [23]:
print('One more trick is to create new features from these categorical variables')

One more trick is to create new features from these categorical variables

In [24]:
df['new_feature'] = (
    df.ord_1.astype(str) +
    "_" +
    df.ord_2.astype(str)
)

In [25]:
df['new_feature']

0         Contributor_3
1         Grandmaster_6
2                 nan_2
3              Novice_4
4         Grandmaster_1
              ...
599995         Novice_2
599996         Novice_0
599997    Contributor_2
599998         Master_6
599999    Contributor_0
Name: new_feature, Length: 600000, dtype: object



> So which categories should we combine? Well, there isn't an easy answer to that. It
depends on your data and the types of features. Some domain knowledge might be
useful for creating features like this. But if you don’t have concerns about memory
and CPU usage, you can go for a greedy approach where you can create many such
combinations and then use a model to decide which features are useful and keep
them.



>  One simple way
to handle NaN values would be to drop them. Well, it’s simple but not ideal. NaN
values may have a lot of information in them, and you will lose it if you just drop
these values. There might also be many situations where most of your data has NaN
values, and thus, you cannot drop rows/samples with NaN values. Another way of
handling NaN values is to treat them as a completely new category. This is the most
preferred way of handling NaN values.

The problem : <br>
A categorical column may have no rare categories in training, but in production you can encounter a new category never seen during training. Your pipeline will throw an error , this is expected behavior for unknown inputs, not necessarily a bug.

In [26]:
print('Add an explicit extra category like "RARE" to represent any unseen/uncommon value')

Add an explicit extra category like "RARE" to represent any unseen/uncommon value

In [27]:
print('Train a separate model using all other features to predict the value of the problematic feature')

Train a separate model using all other features to predict the value of the problematic feature

In [28]:
print('The predicted value will still be one of the categories seen during training No guarantee of good performance ')

The predicted value will still be one of the categories seen during training No guarantee of good performance

In [29]:
print("One More thing can be done which is If you have a fixed test set in advance, combine train + test data just to learn the full set of possible categories")

One More thing can be done which is If you have a fixed test set in advance, combine train + test data just to learn the full set of possible categories

In [30]:
train = pd.read_csv("/content/drive/MyDrive/Projects/Projects/input/train.csv")
test = pd.read_csv("/content/drive/MyDrive/Projects/Projects/input/test.csv")

In [31]:
test.loc[ : , 'target'] = -1

In [32]:
data = pd.concat([train , test]).reset_index(drop = True)

In [33]:
features = [x for x in train.columns if x not in ['id' , 'target']]

In [34]:
for feat in features :
  lbl_enc = preprocessing.LabelEncoder()

  temp_col = data[feat].fillna('NONE').astype(str).values

  data.loc[: , feat] = lbl_enc.fit_transform(temp_col)

In [35]:
train = data[data.target != -1].reset_index(drop = True)
test = data[data.target == -1].reset_index(drop = True)



> It may or may not overfit. There is a
simple fix for that. If you design your cross-validation in such a way that it
replicates the prediction process when you run your model on test data, then it’s
never going to overfit. It means that the first step should be the separation of folds,
and in each fold, you should apply the same pre-processing that you want to apply
to test data. Suppose you want to concatenate training and test data, then in each
fold you must concatenate training and validation data and also make sure that your
validation dataset replicates the test set.

In [36]:
print('This trick works when you have a problem where you already have the test dataset. It must be noted that this trick will not work in a live setting')

This trick works when you have a problem where you already have the test dataset. It must be noted that this trick will not work in a live setting

For example, let’s say
you are in a company that builds a real-time bidding solution (RTB). RTB systems
bid on every user they see online to buy ad space. The features that can be used for
such a model may include pages viewed in a website. Let’s assume that features are
the last five categories/pages visited by the user. In this case, if the website
introduces new categories, we will no longer be able to predict accurately. Our
model, in this case, will fail. A situation like this can be avoided by using an
“unknown” category.

We can treat “NONE” as unknown. So, if during live testing, we get new categories
that we have not seen before, we will mark them as “NONE”.
This is very similar to natural language processing problems. We always build a
model based on a fixed vocabulary. Increasing the size of the vocabulary increases
the size of the model. Transformer models like BERT are trained on ~30000 words
(for English). So, when we have a new word coming in, we mark it as UNK
(unknown).

In [37]:
df.ord_4.fillna('NONE').value_counts()

ord_4
N       39978
P       37890
Y       36657
A       36633
R       33045
U       32897
M       32504
X       32347
C       32112
H       31189
Q       30145
T       29723
O       25610
B       25212
E       21871
K       21676
I       19805
NONE    17930
D       17284
F       16721
W        8268
Z        5790
S        4595
G        3404
V        3107
J        1950
L        1657
Name: count, dtype: int64

In [38]:
print('So When it comes to test data all the new unseen categories will be mapped to "RARE" and missing values will be mapped to "NONE"')

So When it comes to test data all the new unseen categories will be mapped to "RARE" and missing values will be mapped to "NONE"

In [39]:
train.head()

,id,bin_0,bin_1,bin_2,bin_3,bin_4,nom_0,nom_1,nom_2,nom_3,...,nom_9,ord_0,ord_1,ord_2,ord_3,ord_4,ord_5,day,month,target
0,0,0.0,0.0,0.0,0,0,3,5,3,6,...,27,2.0,0,3,3,21,57,5.0,5.0,0
1,1,1.0,1.0,0.0,0,2,3,4,0,5,...,2113,2.0,2,6,5,24,151,6.0,9.0,0
2,2,0.0,1.0,0.0,0,0,3,1,3,0,...,1400,2.0,4,2,14,16,106,4.0,11.0,0
3,3,2.0,0.0,0.0,0,0,3,0,3,3,...,2168,0.0,5,4,1,2,46,2.0,5.0,0
4,4,0.0,2.0,0.0,2,0,3,6,3,2,...,1748,2.0,2,1,8,2,51,4.0,3.0,0

In [40]:
train.target.value_counts()

target
0    487677
1    112323
Name: count, dtype: int64

In [41]:
from sklearn import model_selection

In [42]:
%cd /content/drive/MyDrive/Projects/Projects/src
!python create_folds.py

/content/drive/MyDrive/Projects/Projects/src

In [43]:
df = pd.read_csv('/content/drive/MyDrive/Projects/Projects/input/cat_train_folds.csv')

In [44]:
df.kfold.value_counts()

kfold
0    120000
1    120000
2    120000
3    120000
4    120000
Name: count, dtype: int64

In [45]:
print('In each folder the distribution of targets is same')

In each folder the distribution of targets is same

In [56]:
print('For looking into current working directory')

For looking into current working directory

In [52]:
! pwd

/content/drive/MyDrive/Projects/Projects/src

In [57]:
print('This instantly creates a empty file with the intended name')

This instantly creates a empty file with the intended name

In [92]:
open('ohe_logres.py' , 'w').close()

In [63]:
! python -W ignore ohe_logres.py

AUC for the fold Number 0 is 0.7866358647589423
AUC for the fold Number 1 is 0.7865600969315559
AUC for the fold Number 2 is 0.7861530100005418
AUC for the fold Number 3 is 0.7868470159792775
AUC for the fold Number 4 is 0.7853613856204904

In [68]:
open('lbl_rf.py' , 'w').close()

In [75]:
! python -W ignore ohe_rf.py

AUC for the fold Number 0 is 0.7168717847907775
AUC for the fold Number 1 is 0.7175630425876649
AUC for the fold Number 2 is 0.7172094488363624
AUC for the fold Number 3 is 0.7131056758762977
AUC for the fold Number 4 is 0.7162112831804767

In [77]:
print('The random forest model, without any tuning of hyperparameters, performs a lot worse than simple logistic regression.')

The random forest model, without any tuning of hyperparameters, performs a lot worse than simple logistic regression.



> In our implementation of
random forest, the folds take a much longer time to complete compared to logistic
regression. So, we are not only losing on AUC but also taking much longer to
complete the training. Please note that inference is also time-consuming with
random forest and it also takes much larger space


> A fan of
random forest would begin with it here and will ignore logistic regression model
thinking it’s a very simple model that cannot bring any value better than random
forest. That kind of person will make a huge mistake

In [78]:
print('Earlier we trained rf with label encoder but this time we will do with one hot encoding and doing svd on the sparse matrix')

Earlier we trained rf with label encoder but this time we will do with one hot encoding and doing svd on the sparse matrix

In [81]:
! pwd

/content/drive/MyDrive/Projects/Projects/src

In [82]:
open('ohe_svd_rf.py' , 'w').close()

In [122]:
# ! python -W ignore ohe_svd_rf.py

It seems like the best method for this problem is one-
hot encoding with logistic regression. Random forest appears to be taking way

In [88]:
open('lbl_xgb.py' , 'w').close()

In [93]:
! python -W ignore lbl_xgb.py

AUC for fold number 0 is 0.7599706396120349
AUC for fold number 1 is 0.7606624959807375
AUC for fold number 2 is 0.7590894412160718
AUC for fold number 3 is 0.759637314190523
AUC for fold number 4 is 0.7617213210604681

### Push to Github

In [104]:
email = userdata.get('email')

!git config --global user.email "{email}"
!git config --global user.name "Devil-92"

In [99]:
%cd /content/drive/MyDrive/Projects/Cat-in-the-Dat

/content/drive/MyDrive/Projects/Cat-in-the-Dat

In [110]:
token = userdata.get('GithubToken')

In [111]:
!git remote set-url origin https://Devil-92:{token}@github.com/Devil-92/Categorical_Feature_Encoding_Challenge_II.git

In [118]:
%%writefile .gitignore
input/
models/
__pycache__/
.ipynb_checkpoints/
*.pyc

Writing .gitignore

In [121]:
!git init
!git add .
!git commit -m "Initial commit: project structure with src, notebooks (data excluded)"

!git remote add origin https://Devil-92:{token}@github.com/Devil-92/Categorical_Feature_Encoding_Challenge_II.git
!git branch -M main
!git push -u origin main --force

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /content/drive/MyDrive/Projects/Cat-in-the-Dat/.git/
[master (root-commit) 287328e] Initial commit: project structure with src, notebooks (data excluded)
 6 files changed, 179 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 src/create_folds.py
 create mode 100644 src/lbl_rf.py
 create mode 100644 src/lbl_xgb.py
 create mode 100644 src/ohe_logres.py
 create mode 100644 src/ohe_svd_rf.py
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 2 threads
Compressing objects: 100% (8/8), done.
Writing objects: 100% (9/9), 2.44 KiB | 250.00 KiB/s, done.
Total 9 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/Devil-92/Categorical_Feature_Encoding_Challenge_II.git
 + 5de0079...287328e main -> main (forced update)
branch 'main' set up to track 'origin/main'.